name: Test calc app
run-name: ${{ github.actor }} triggered test!
on: [push]
jobs:
  Jest-Test-Calc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Instalar dependências
      run: npm install

    - name: Rodar testes
      run: npm run coverage

    - name: Jest Resultas
      uses: MishaKav/jest-coverage-comment@main